### ISSUE TITLE
Stop bouncing animation on TinderLikeCard

### ISSUE THREAD

**Issue by paulgaumer** [yoloten/react-stack-cards#10]
HI @yoloten, is there a way to deactivate the bouncing animation on the TinderLikeCard?

**Comment by yoloten** [comment]
@paulgaumer, hi. The bouncing used just in some of the animation types. That's the way they were designed. But you can use another types that don't have any bouncing :)
For instance: You can replace swipeCornerDownRight with swipeRightRotate

**Comment by paulgaumer** [comment]
Awesome! Exactly what I needed! Thanks a lot for the quick reply 🙏
