### ISSUE TITLE
Adding Link component does not work

### ISSUE THREAD

**Issue by nirajupadhyay11** [yoloten/react-stack-cards#12]
Hi,

I modified the following StackCard code to include the call to "Link" component form react-router-dom so that user can navigate to another URL when he clicks on the card. But, adding the component code did not have any effect.

`import React from "react";
import { Link } from "react-router-dom";`

`const solararray = [earthwebp, solarsystemwebp, moonwebp, earthwebp]`

` <StackCard
          images={solararray}
          width="350"
          height="240"
          direction="accordeonLeft"
          component={Link}
          to="/solarsystem"          
        ></StackCard>`

Could you please tell me what the issue could be?

**Comment by yoloten** [comment]
You should wrap StackCard with Link component. That's not an issue of StackCard component
