### ISSUE TITLE
Animation effect not smooth

### ISSUE THREAD

**Issue by nirajupadhyay11** [yoloten/react-stack-cards#13]
Hi,

I added <StackCard> to my react project but the animation effect is not smooth at all. I am using the same images as you have used in your demo page and did not change any other settings from the examples but still the effect is not as smooth as the one on your demo page. 

I am using version 1.0.8. 

I also get the following error message in the console everytime the stackcard animates

![image](https://user-images.githubusercontent.com/26413069/80862283-60c6a880-8c91-11ea-8d98-a52cd58f6694.png)

Is there anything that I can do to improve the animations?

Thanks,
Niraj

**Comment by yoloten** [comment]
Hi,
1. Animation. Actually I tested in different kinds of computers including old ones with 2gb RAM and weak graphics card. Everything worked pretty well. So it may be some problems in your machine.
2. Yeah, that error message started to appear after last package update. Unfortunately I don't have time now to figure out what's went wrong :(
