### ISSUE TITLE
[Suggestion] Remove alert("Hello") from examples

### ISSUE THREAD

**Issue by sesm** [yoloten/react-stack-cards#5]
Is `alert("Hello")` really necessary in examples? IMO it spoils the impression for otherwise a very good demo.

**Comment by yoloten** [comment]
> Is `alert("Hello")` really necessary in examples? IMO it spoils the impression for otherwise a very good demo.

Yeah, you are right alert is unnecessary here. When I put it I thought that it would be cool to show onClick feature but now I see that I was wrong. Will change it soon. Thank you)
