### ISSUE TITLE
card position issues in bigger cards

### ISSUE THREAD

**Issue by SabaRathnamK** [yoloten/react-stack-cards#7]
Card transform position is incorrect for bigger cards..

[https://user-images.githubusercontent.com/39154180/66203822-ec119880-e6c6-11e9-9142-f466589fc15c.png](url)

But it is working for smaller cards

[https://user-images.githubusercontent.com/39154180/66203946-38f56f00-e6c7-11e9-9f05-45df5c8ac0e1.png](url)

**Comment by yoloten** [comment]
Hi, @SabaRathnamK 
I fixed bag that you mentioned. Thank you!

**Comment by SabaRathnamK** [comment]
I implemented this updated version but it is creating another issue.. that is creating empty containers beyond the limit.

![image](https://user-images.githubusercontent.com/39154180/66474365-cb728580-eaae-11e9-9079-0225f05de6ff.png)

and also the gap between cards differs as we change the screen size..

![image](https://user-images.githubusercontent.com/39154180/66474456-fb218d80-eaae-11e9-98c1-9bcdeeb04525.png)

**Comment by SabaRathnamK** [comment]
Thanks for your immediate update :)
